version: "3.9"
   
services:
  shareloader:
    image: thewhobox/shareloader:latest
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /share/Emby:/emby
    - /share/ShareLoader:/shareloader
    environment:
    - DDL_APIKEY=xxxx
    - OMDB_APIKEY=xxxx
    ports:
    - "18000:80"
    restart: always