name: Docker Image CI

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ShareLoader/
          platforms: linux/amd64,linux/arm64,linux/armv7,linux/armv8
          push: true
          tags: thewhobox/shareloader:latest
