name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: [ "publish" ]
  pull_request:
    branches: [ "publish" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v2
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5.0.0
      with:
        file: ShareLoader/Dockerfile
        platforms: linux
        push: true
        tags: thewhobox/shareloader:latest
